# Generated by Django 3.2.4 on 2021-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(null=True)),
                ('writer', models.CharField(max_length=20, null=True)),
                ('context', models.TextField()),
                ('media', models.ImageField(blank=True, null=True, upload_to='feed/')),
            ],
        ),
    ]
