# Generated by Django 3.2.4 on 2021-06-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0002_auto_20210629_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
